include:
  - project: 'clci/gitlab-ci'
    ref: release/v2-dev
    file:
      - definitions.gitlab-ci.yml
  - project: 'clci/gitlab-ci'
    ref: release/v2-dev
    file:
      - test-pipeline.gitlab-ci.yml
      - release-pipeline.gitlab-ci.yml
    rules:
      - if: '$PIPELINE_TYPE != "clpm-dep-update"'
  - project: 'clci/gitlab-ci'
    ref: release/v2-dev
    file:
      - clpm-dep-update-pipeline.gitlab-ci.yml
    rules:
      - if: '$PIPELINE_TYPE == "clpm-dep-update"'

variables:
  # Neither of these have package local nickname support.
  CLCI_TEST_CLISP: "no"
  CLCI_TEST_CMUCL: "no"
  CLCI_ABCL_TAG: "jdk8"

# This section is not strictly required, but prevents Gitlab CI from launching
# multiple redundent pipelines when a Merge Request is opened.
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'

generate docs:
  image: clfoundation/sbcl
  extends:
    - .clci sbcl
    - .clci clpm script
  variables:
    CLPM_SCRIPT: scripts/generate-docs.lisp
  artifacts:
    paths:
      - docs/

publish docs:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(\.[0-9]+)*(-.*)?$/'
  needs:
    - "test blocker:release:clci"
  trigger: cl-tar/cl-tar-site
  variables:
    CL_TAR_TAG: $CI_COMMIT_TAG
    CL_TAR_PIPELINE: $CI_PIPELINE_ID

build release:
  image: daewok/static-sbcl:2.1.9
  extends:
    - .clci sbcl
    - .clci clpm script
  variables:
    ASDF_VERSION: "3.3.4"
    CLPM_SCRIPT: scripts/build-release.lisp
  artifacts:
    paths:
      - releases/
